#https://github.com/marketplace/actions/github-tag-bump
name: Bump version

on:
  push:
    branches: [ develop ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@develop

    # Runs a single command using the runners shell
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.22.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        RELEASE_BRANCHES: release/*
        INITIAL_VERSION: 1.0.0
